### ISSUE TITLE
Consider adding Google News cybersecurity topic feed

### ISSUE THREAD

**Issue by impredicative** [FingerlessGlov3s/SecurityFeedIRCBot#1]
Web page: https://news.google.com/topics/CAAqBwgKMKz3gQsw5KP-Ag?hl=en

RSS URL: https://news.google.com/rss/topics/CAAqBwgKMKz3gQsw5KP-Ag?hl=en

Possible name of feed: gNews

Note that adding a token to the env file requires recreating (and not just restarting) the container.

**Comment by impredicative** [comment]
Note that adding this feed can require adding more Bitly tokens. I'm now testing with >9 tokens.

**Comment by impredicative** [comment]
Note that adding a token to the env file requires recreating (and not just restarting) the container.

**Comment by FingerlessGlov3s** [comment]
Added feed as gNews for now and updated bot to 0.4.0 and added more tokens.
